FROM oven/bun:1.3.14

WORKDIR /workspace

COPY apps/preview-build/entrypoint.sh  /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 5173
CMD ["/usr/local/bin/entrypoint.sh"]